#!/bin/bash

echo -n "Please enter the first integer:"
read num1

echo -n "Please enter the second integer:"
read num2

echo -n "Please enter the third integer:"
read num3

if [[ $num1 -gt $num2 && $num1 -gt $num3 ]]
then
  echo "$num1"
elif [[ $num2 -gt $num1 && $num2 -gt $num3 ]]
then
  echo "$num2"
else
  echo "$num3"
fi
